From d707525374deabe3128acee728666ecac7f27877 Mon Sep 17 00:00:00 2001
From: Heinrich Schuchardt <xypron.glpk@gmx.de>
Date: Thu, 6 Sep 2018 20:17:09 +0200
Subject: [PATCH 1/1] test/py: typo occured

%s/occured/occurred/

Signed-off-by: Heinrich Schuchardt <xypron.glpk@gmx.de>
---
 test/py/tests/test_efi_selftest.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/test/py/tests/test_efi_selftest.py b/test/py/tests/test_efi_selftest.py
index de3272402e..994d2e2241 100644
--- a/test/py/tests/test_efi_selftest.py
+++ b/test/py/tests/test_efi_selftest.py
@@ -16,7 +16,7 @@ def test_efi_selftest(u_boot_console):
 	u_boot_console.run_command(cmd='bootefi selftest', wait_for_prompt=False)
 	m = u_boot_console.p.expect(['Summary: 0 failures', 'Press any key'])
 	if m != 0:
-		raise Exception('Failures occured during the EFI selftest')
+		raise Exception('Failures occurred during the EFI selftest')
 	u_boot_console.run_command(cmd='', wait_for_echo=False, wait_for_prompt=False);
 	m = u_boot_console.p.expect(['resetting', 'U-Boot'])
 	if m != 0:
@@ -104,5 +104,5 @@ def test_efi_selftest_text_input(u_boot_console):
 				   wait_for_prompt=False)
 	m = u_boot_console.p.expect(['Summary: 0 failures', 'Press any key'])
 	if m != 0:
-		raise Exception('Failures occured during the EFI selftest')
+		raise Exception('Failures occurred during the EFI selftest')
 	u_boot_console.restart_uboot();
-- 
2.18.0

